// <auto-generated />
using System;
using CoffeePaymentSystem.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CoffeePaymentSystem.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.5");

            modelBuilder.Entity("CoffeePayments.Models.Coworker", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Balance")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateJoined")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("DrinkCost")
                        .HasColumnType("TEXT");

                    b.Property<string>("FavoriteDrink")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Coworkers");
                });

            modelBuilder.Entity("CoffeePayments.Models.PaymentHistoryEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("AmountPaid")
                        .HasColumnType("TEXT");

                    b.Property<int>("CoworkerId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DatePaid")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsSkip")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CoworkerId");

                    b.ToTable("PaymentHistory");
                });

            modelBuilder.Entity("CoffeePayments.Models.PaymentHistoryEntry", b =>
                {
                    b.HasOne("CoffeePayments.Models.Coworker", "Payer")
                        .WithMany()
                        .HasForeignKey("CoworkerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Payer");
                });
#pragma warning restore 612, 618
        }
    }
}
